# Generated by Django 2.2.18 on 2021-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=256)),
                ("address", models.TextField()),
                ("contract_price", models.BigIntegerField()),
                ("closing_date", models.DateField()),
                ("status", models.TextField()),
            ],
        ),
    ]
